// Fridge
export const FRIDGE_FETCH_ITEMS = 'FRIDGE_FETCH_ITEMS';
export const FRIDGE_FETCH_ITEMS_ASYNC = 'FRIDGE_FETCH_ITEMS_ASYNC';
export const FRIDGE_FETCH_ITEMS_SUCCESS = 'FRIDGE_FETCH_ITEMS_SUCCESS';
export const FRIDGE_FETCH_ITEMS_ERROR = 'FRIDGE_FETCH_ITEMS_ERROR';

export const FRIDGE_ADD_ITEM = 'FRIDGE_ADD_ITEM';
export const FRIDGE_ADD_ITEM_ASYNC = 'FRIDGE_ADD_ITEM_ASYNC';
export const FRIDGE_ADD_ITEM_SUCCESS= 'FRIDGE_ADD_ITEM_SUCCESS';
export const FRIDGE_ADD_ITEM_ERROR = 'FRIDGE_ADD_ITEM_ERROR';

export const FRIDGE_FETCH_ITEM = 'FRIDGE_FETCH_ITEM';
export const FRIDGE_FETCH_ITEM_ASYNC = 'FRIDGE_FETCH_ITEM_ASYNC';
export const FRIDGE_FETCH_ITEM_SUCCESS= 'FRIDGE_FETCH_ITEM_SUCCESS';
export const FRIDGE_FETCH_ITEM_ERROR = 'FRIDGE_FETCH_ITEM_ERROR';

export const FRIDGE_UPDATE_ITEM = 'FRIDGE_UPDATE_ITEM';
export const FRIDGE_UPDATE_ITEM_ASYNC = 'FRIDGE_UPDATE_ITEM_ASYNC';
export const FRIDGE_UPDATE_ITEM_SUCCESS= 'FRIDGE_UPDATE_ITEM_SUCCESS';
export const FRIDGE_UPDATE_ITEM_ERROR = 'FRIDGE_UPDATE_ITEM_ERROR';
