// Fridge
export const FRIDGE_FETCH_ITEMS = 'FRIDGE_FETCH_ITEMS'
export const FRIDGE_FETCH_ITEMS_SUCCESS = 'FRIDGE_FETCH_ITEMS_SUCCESS'
export const FRIDGE_FETCH_ITEMS_ERROR = 'FRIDGE_FETCH_ITEMS_ERROR'

export const FRIDGE_ADD_ITEM = 'FRIDGE_ADD_ITEM'
export const FRIDGE_ADD_ITEM_SUCCESS = 'FRIDGE_ADD_ITEM_SUCCESS'
export const FRIDGE_ADD_ITEM_ERROR = 'FRIDGE_ADD_ITEM_ERROR'

export const FRIDGE_FETCH_ITEM = 'FRIDGE_FETCH_ITEM'
export const FRIDGE_FETCH_ITEM_SUCCESS = 'FRIDGE_FETCH_ITEM_SUCCESS'
export const FRIDGE_FETCH_ITEM_ERROR = 'FRIDGE_FETCH_ITEM_ERROR'

export const FRIDGE_UPDATE_ITEM = 'FRIDGE_UPDATE_ITEM'
export const FRIDGE_UPDATE_ITEM_SUCCESS = 'FRIDGE_UPDATE_ITEM_SUCCESS'
export const FRIDGE_UPDATE_ITEM_ERROR = 'FRIDGE_UPDATE_ITEM_ERROR'

export const FRIDGE_DELETE_ITEM = 'FRIDGE_DELETE_ITEM'
export const FRIDGE_DELETE_ITEM_SUCCESS = 'FRIDGE_DELETE_ITEM_SUCCESS'
export const FRIDGE_DELETE_ITEM_ERROR = 'FRIDGE_DELETE_ITEM_ERROR'

export const USER_ACCESS = 'USER_ACCESS'
export const USER_ACCESS_SUCCESS = 'USER_ACCESS_SUCCESS'
export const USER_ACCESS_ERROR = 'USER_ACCESS_ERROR'

export const GIVE_USER_ACCESS = 'GIVE_USER_ACCESS'
export const GIVE_USER_ACCESS_SUCCESS = 'GIVE_USER_ACCESS_SUCCESS'
export const GIVE_USER_ACCESS_ERROR = 'GIVE_USER_ACCESS_ERROR'

export const FRIDGES_WITH_ACCESS = 'FRIDGES_WITH_ACCESS'
export const FRIDGES_WITH_ACCESS_SUCCESS = 'FRIDGES_WITH_ACCESS_SUCCESS'
export const FRIDGES_WITH_ACCESS_ERROR = 'FRIDGES_WITH_ACCESS_ERROR'

export const RESET_LOGOUT = 'RESET_LOGOUT'

// AUTH
export const AUTH_SIGNUP = 'AUTH_SIGNUP'
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_SIGNUP_ERROR = 'AUTH_SIGNUP_ERROR'
export const AUTH_UPDATE_SIGNUP = 'AUTH_UPDATE_SIGNUP'

export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR'

export const AUTH_IS_LOGGED_IN = 'AUTH_IS_LOGGED_IN'
export const AUTH_IS_LOGGED_IN_SUCCESS = 'AUTH_IS_LOGGED_IN_SUCCESS'
export const AUTH_IS_LOGGED_IN_ERROR = 'AUTH_IS_LOGGED_IN_ERROR'